M48
; DRILL file {KiCad 8.0.8} date 2025-11-20T00:18:14-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-11-20T00:18:14-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1000
%
G90
G05
T1
X5.1433Y-2.7363
X5.1433Y-3.4363
T2
X6.9433Y-2.7363
X6.9433Y-3.4363
M30
